"""Constantes y helpers internos del notebook fuente.

Estos símbolos eran globales del notebook. Aquí se preservan
para mantener compatibilidad con clases que los referencian.
"""

from __future__ import annotations

# ────────────────────────────────────────────────────────────
# ADMINISTRATIVE_NOISE  (origen: notebook celda [113], tipo: assign)

# ────────────────────────────────────────────────────────────
# STOPWORDS_BASIC  (origen: notebook celda [113], tipo: assign)
# ────────────────────────────────────────────────────────────
STOPWORDS_BASIC = {
    # Artículos y preposiciones español
    "THE",
    "OF",
    "AND",
    "DE",
    "LA",
    "EL",
    "LOS",
    "LAS",
    "EN",
    "Y",
    "E",
    "O",
    "U",
    "DEL",
    "PARA",
    "POR",
    "CON",
    "AL",
    "UN",
    "UNA",
    "UNOS",
    "UNAS",
    "LO",
    "SU",
    "SUS",
    "SOBRE",
    "ENTRE",
    "SIN",
    "D",
    "L",
    "DA",
    "DI",
    # Artículos y preposiciones inglés
    "IN",
    "AT",
    "BY",
    "FOR",
    "TO",
    "AS",
    "ON",
    "WITH",
    "FROM",
    "A",
    "AN",
    # Otros comunes
    "MC",
}

# ────────────────────────────────────────────────────────────
# LEGAL_SUFFIXES  (origen: notebook celda [113])
# ────────────────────────────────────────────────────────────
LEGAL_SUFFIXES = {
    # ===== SOCIEDADES ANÓNIMAS Y SIMPLIFICADAS =====
    "SAS",
    "S.A.S.",
    "S.A.S",
    "S A S",
    "S-A-S",
    "S. A. S.",
    "SAS.",
    "S.A.S. BIC",
    "SAS BIC",
    "S.A.S BIC",
    "SOCIEDAD POR ACCIONES SIMPLIFICADA",
    "SA",
    "S.A.",
    "S.A",
    "S A",
    "S. A.",
    "S-A",
    "SOCIEDAD ANONIMA",
    "SOCIEDAD ANÓNIMA",
    # ===== LIMITADAS =====
    "LTDA",
    "LTDA.",
    "LIMITADA",
    "LTD",
    "LTD.",
    "LIMITED",
    "L.T.D.A.",
    "L.T.D.A",
    "CIA LTDA",
    "Y CIA LTDA",
    "& CIA LTDA",
    # Errores tipográficos comunes
    "LTA",
    "LMT",
    "LMTDA",
    "LTM",
    "LIMITDA",
    "LIMTADA",
    "LDTDA",
    "L.TDA",
    "L TDA",
    # ===== EMPRESAS UNIPERSONALES =====
    "EU",
    "E.U.",
    "E.U",
    "E U",
    "E. U.",
    "EMPRESA UNIPERSONAL",
    "UNIPERSONAL",
    # ===== COMERCIALIZADORAS INTERNACIONALES (Muy común en Colombia) =====
    "CI",
    "C.I.",
    "C.I",
    "C I",
    "C. I.",
    "S.C.I.",
    "SCI",
    "S.C.I",
    "S. C. I.",
    "COMERCIALIZADORA INTERNACIONAL",
    "SOCIEDAD DE COMERCIALIZACION INTERNACIONAL",
    # ===== COMANDITARIAS =====
    "SCS",
    "S.C.S",
    "S.C.S.",
    "S EN C",
    "S. EN C.",
    "S EN C.",
    "S. EN C",
    "SCA",
    "S.C.A.",
    "S.C.A",
    "S C A",
    "S. C. A.",
    "S. EN C. A.",
    "S EN C A",
    "SOCIEDAD EN COMANDITA",
    "SOCIEDAD EN COMANDITA SIMPLE",
    "SOCIEDAD EN COMANDITA POR ACCIONES",
    "COMANDITA SIMPLE",
    # ===== ENTIDADES PÚBLICAS Y ESPECIALES =====
    "ESP",
    "E.S.P.",
    "E.S.P",
    "EMPRESA DE SERVICIOS PUBLICOS",
    "E.S.E.",
    "E.S.E",
    "ESE",
    "EMPRESA SOCIAL DEL ESTADO",
    "I.P.S.",
    "I.P.S",
    "IPS",
    "INSTITUCION PRESTADORA DE SALUD",
    # ===== INTERMEDIACIÓN ADUANERA (Crítico para Colombia) =====
    "S.I.A.",
    "S.I.A",
    "SIA",
    "SOCIEDAD DE INTERMEDIACION ADUANERA",
    "U.A.P.",
    "UAP",
    "USUARIO ADUANERO PERMANENTE",
    "ALTEX",
    "USUARIO ALTEX",
    "USUARIO ALTAMENTE EXPORTADOR",
    # ===== BENEFICIO E INTERÉS COLECTIVO =====
    "BIC",
    "B.I.C.",
    "B.I.C",
    "BENEFICIO E INTERES COLECTIVO",
    # ===== SUCURSALES Y FILIALES =====
    "SUCURSAL",
    "SUCURSAL COLOMBIA",
    "SUCURSAL DE COLOMBIA",
    "SUCURSAL EN COLOMBIA",
    "BRANCH",
    "FILIAL",
    # ===== COOPERATIVAS Y ASOCIATIVAS =====
    "COOP",
    "COOPERATIVA",
    "PRECOOPERATIVA",
    "CTA",
    "C.T.A.",
    "COOPERATIVA DE TRABAJO ASOCIADO",
    "E.A.T.",
    "EMPRESA ASOCIATIVA DE TRABAJO",
    "FONDO DE EMPLEADOS",
    "ASOCIACION MUTUAL",
    # ===== COMPAÑÍAS Y SOCIEDADES =====
    "CIA",
    "CIA.",
    "COMPAÑIA",
    "COMPANIA",
    "COMPAÐIA",
    "COMPA IA",
    "COMAPNIA",
    "Y CIA",
    "& CIA",
    "Y COMPAÑIA",
    "Y COMPANIA",
    "& COMPANY",
    "& CO",
    "SOCIEDAD",
    # ===== FORMAS INTERNACIONALES =====
    "INC",
    "INC.",
    "INCORPORATED",
    "CORP",
    "CORP.",
    "CORPORATION",
    "LLC",
    "L.L.C.",
    "SPA",
    "S.P.A.",
    "S.P.A",
    "SAU",
    "S.A.U.",
    "S.A.U",
    "SRL",
    "S.R.L.",
    "SLU",
    "S.L.U.",
    "SL",
    "S.L.",
    # ===== OTRAS ESPECIALES =====
    "ZOMAC",  # Zonas Más Afectadas por el Conflicto
}

# ────────────────────────────────────────────────────────────
# ORGANIZATIONAL_TERMS  (origen: notebook celda [113])
# ────────────────────────────────────────────────────────────
ORGANIZATIONAL_TERMS = {
    # ===== FORMAS ORGANIZACIONALES GENÉRICAS =====
    "GRUPO",
    "GROUP",
    "HOLDING",
    "HOLDINGS",
    "ORGANIZACION",
    "ORGANIZACIÓN",
    "ORGANIZACIONAL",
    "EMPRESA",
    "EMPRESAS",
    "EMPRESARIAL",
    "CORPORACION",
    "CORPORACIÓN",
    "CONSORCIO",
    "UNION TEMPORAL",
    "UNIÓN TEMPORAL",
    "UT",
    "TEMPORAL",
    "ASOCIACION",
    "ASOCIACIÓN",
    "FUNDACION",
    "FUNDACIÓN",
    # ===== ACTIVIDADES COMERCIALES GENÉRICAS =====
    "COMERCIAL",
    "COMERCIALIZACION",
    "COMERCIALIZADORA",
    "COMERCIALIDZADORA",
    "COMERCIALIZDORA",
    "COEMRCIALIZACION",
    "COMER",
    "DISTRIBUIDORA",
    "DISTRIBUCIONES",
    "DISTRIBUCION",
    "DIST",
    "IMPORTADORA",
    "IMPORTACIONES",
    "IMPORT",
    "IMPO",
    "IMPOR",
    "EXPORTADORA",
    "EXPORTACIONES",
    "EXPORT",
    "EXPO",
    "EXPOR",
    "TRADING",
    "TRADE",
    "MARKETING",
    "REPRESENTACIONES",
    "REPRESENTACION",
    "SUMINISTROS",
    "PROVEEDORA",
    "PROVEEDORES",
    # ===== MANUFACTURA E INDUSTRIA =====
    "INDUSTRIAS",
    "INDUSTRIA",
    "INDUSTRIAL",
    "INDUSTRIALES",
    "MANUFACTURAS",
    "MANUFACTURA",
    "MANUFACTURERA",
    "FABRICA",
    "FABRICACION",
    "PRODUCTOS",
    "PRODUCTO",
    "PRODUACTOS",
    "PRODCUTOS",
    # ===== SERVICIOS =====
    "SERVICIOS",
    "SERVICIO",
    "SERVICE",
    "SERVICES",
    "SERVIR",
    "CONSERVICIOS",
    "COSERVICIOS",
    "SOLUCIONES",
    "SOLUTIONS",
    "MULTISERVICIOS",
    # ===== INVERSIONES Y CAPITAL =====
    "INVERSIONES",
    "INVERSORA",
    "INVER",
    "INVESTMENT",
    "INVESTMENTS",
    "CAPITAL",
    "VENTURES",
    "BUSINESS",
    # ===== LOGÍSTICA Y TRANSPORTE =====
    "LOGISTICA",
    "LOGISTICS",
    "TRANSPORTE",
    "TRANSPORTES",
    "TRANSPORTADORES",
    "TRANSPORTADORA",
    "OPERADOR",
    "OPERACIONES",
    "CARGA",
    "CARGO",
    "ENVIOS",
    # ===== CONSTRUCCIÓN E INGENIERÍA =====
    "CONSTRUCTORA",
    "CONSTRUCTOR",
    "CONSTRUCTORES",
    "CONSTRUCCION",
    "CONSTRUCCIONES",
    "CONSTUCTORES",
    "INGENIERIA",
    "INGENIEROS",
    "INGENERIA",
    "INSENTERIA",
    "INGECON",
    "ENGINEERING",
    "ARQUITECTURA",
    "ARQUITECTOS",
    "PROYECTOS",
    "PROYECTO",
    "PROJECTS",
    "ESTRUCTURAS",
    # ===== CONSULTORÍA Y PROFESIONALES =====
    "CONSULTORES",
    "CONSULTORIA",
    "CONSULTING",
    "ASESORIAS",
    "ASESORES",
    "ABOGADOS",
    "PROFESIONAL",
    # ===== ESTABLECIMIENTOS =====
    "ALMACEN",
    "ALMACENES",
    "TIENDA",
    "TIENDAS",
    "BODEGA",
    "BODEGAS",
    "DEPÓSITO",
    "DEPOSITO",
    "CENTRO",
    "CENTER",
    "PUNTO",
    "OUTLET",
    "TALLER",
    "TALLERES",
    "INSTITUTO",
    "INSTITUCION",
    "DIVISION",
    "DEPARTAMENTO",
    "DEPARTMENT",
    # ===== AGRO Y ALIMENTOS =====
    "AGRICOLA",
    "AGRICOLAS",
    "AGRI COLA",
    "AGROINDUSTRIAL",
    "AGROINDUSTRIALES",
    "AGROINDUSTRIA",
    "AGRO",
    "AGROPECUARIA",
    "CULTIVOS",
    "FINCA",
    "HACIENDA",
    "GRANJA",
    "AVICOLA",
    "GANADERA",
    "ALIMENTOS",
    "ALIMENTACION",
    "COMESTIBLES",
    "FOODS",
    "FOOD",
    "BEBIDAS",
    "DRINKS",
    "CARNES",
    "FRUTAS",
    "FRUITS",
    "CAFE",
    "COFFEE",
    "CAFETERA",
    "CAFICULTORES",
    "CAFICULT",
    # ===== FLORES =====
    "FLORES",
    "FLOWERS",
    "FLOWER",
    "FLORWERS",
    "FLOWES",
    "FLORICULTURA",
    "ROSAS",
    "ROSES",
    "PLANTAS",
    "FLORAL",
    # ===== TEXTILES Y CONFECCIONES =====
    "TEXTILES",
    "TEXTILE",
    "TEXTIL",
    "CONFECCIONES",
    "CONFECCI0NES",
    "CONFECCCIONES",
    "MODA",
    "FASHION",
    "DISEÑO",
    "DESIGN",
    "CREACIONES",
    "VARIEDADES",
    "JEANS",
    "APPAREL",
    "WEAR",
    "CLOTHING",
    "CALZADO",
    "ZAPATOS",
    "CUEROS",
    "LEATHER",
    "PIELES",
    "MARROQUINERIA",
    # ===== PLÁSTICOS Y EMPAQUES =====
    "PLASTICOS",
    "PLASTICS",
    "EMPAQUES",
    "PACKAGING",
    "ENVASES",
    # ===== QUÍMICA Y FARMACIA =====
    "QUIMICA",
    "QUIMICOS",
    "QUINICOS",
    "QUIMIMCOS",
    "CHEMICALS",
    "CHEMICAL",
    "PHARMA",
    "FARMACEUTICA",
    "FARMACIA",
    "DROGUERIA",
    "LABORATORIO",
    "LABORATORIOS",
    # ===== MINERÍA Y ENERGÍA =====
    "MINERA",
    "MINEROS",
    "MINERALES",
    "CARBONES",
    "COAL",
    "OIL",
    "GAS",
    "PETROLEUM",
    "ENERGIA",
    "ENERGIAS",
    "ENERGY",
    "POWER",
    "SOLAR",
    # ===== TECNOLOGÍA =====
    "TECNOLOGIA",
    "TECHNOLOGY",
    "SYSTEMS",
    "SISTEMAS",
    "SOFTWARE",
    "DIGITAL",
    "NETWORKS",
    "COMUNICACIONES",
    "TELECOMUNICACIONES",
    # ===== SEGURIDAD =====
    "SEGURIDAD",
    "SECURITY",
    "VIGILANCIA",
    # ===== INMOBILIARIA =====
    "INMOBILIARIA",
    "INMOBILIARIAS",
    "PROPIEDAD",
    "RAIZ",
    # ===== AUTOMOTOR =====
    "AUTOMOTORES",
    "MOTOS",
    "AUTOPARTES",
    "REPUESTOS",
    # ===== SALUD =====
    "SALUD",
    "CLINICA",
    "HOSPITAL",
    "MEDICA",
    "MEDICO",
    "MEDICOS",
    # ===== OTROS SECTORES =====
    "ARTESANIAS",
    "JOYERIA",
    "ACCESORIOS",
    "FERRETERIA",
    "MATERIALES",
    "DOTACIONES",
    "HOTEL",
    "RESTAURANTE",
    "CAFETERIA",
    # ===== ADUANAS Y COMERCIO EXTERIOR =====
    "ADUANAS",
    "ADUANA",
    "ADUANERA",
    "ADUANEROS",
    "ADUANAMIENTOS",
    "AGENCIA DE ADUANAS",
    "AGENCIA",
    "INTERMEDIACION",
    "USUARIO",
    "ZONA",
    "FRANCA",
    "ZF",
    # ===== ALCANCE GEOGRÁFICO =====
    "INTERNACIONAL",
    "INTERNATIONAL",
    "INTERNACIONMAL",
    "INTERNACIOANAL",
    "INTERNACIONALES",
    "GLOBAL",
    "MUNDIAL",
    "WORLD",
    "WORLDWIDE",
    "COLOMBIA",
    "COLOMBIANA",
    "COLOMBIANO",
    "COLOMBIANOS",
    "COLMBIA",
    "CBIA",
    "CLOMBIA",
    "COLOBIA",
    "COLONBIA",
    "COLOMBI",
    "COLOMBOIANA",
    "NACIONAL",
    "ANDINA",
    "LATIN",
    "LATINOAMERICA",
    "AMERICA",
    "CARIBE",
    "NORTE",
    "SUR",
    "OCCIDENTE",
    "ORIENTE",
    # ===== CALIFICATIVOS GENÉRICOS =====
    "INTEGRAL",
    "INTEGRALES",
    "GENERAL",
    "GENERALES",
    "ESPECIALIZADA",
    # ===== ESTADOS LEGALES (Para limpieza) =====
    "REORGANIZACION",
    "RESTRUCTURACION",
    "REESTRUCTURACION",
    "LIQUIDACION",
    "LIQUIDACI N",
    "ACUERDO",
}

# ────────────────────────────────────────────────────────────
# ADMINISTRATIVE_NOISE  (origen: notebook celda [113], tipo: assign)
# ────────────────────────────────────────────────────────────
ADMINISTRATIVE_NOISE = [
    "EN LIQUIDACION",
    "EN LIQUIDACIÓN",
    "EN REORGANIZACION",
    "EN REORGANIZACIÓN",
    "EN REORGANIZACION EMPRESARIAL",
    "EN REORGANIZACIÓN EMPRESARIAL",
    "EN REESTRUCTURACION",
    "EN REESTRUCTURACIÓN",
    "EN CONCORDATO",
    "EN TOMA DE POSESION",
    "EN TOMA DE POSESIÓN",
    "EN ACUERDO DE REESTRUCTURACION",
    "EN ACUERDO DE REESTRUCTURACIÓN",
    "LEY 1116",
    "INSOLVENCIA",
    "PERSONA NATURAL",
    "NO DEFINIDO",
    "(EN BLANCO)",
    "EN BLANCO",
]

# ────────────────────────────────────────────────────────────
# CLEANING_MODES  (origen: notebook celda [113], tipo: assign)
# ────────────────────────────────────────────────────────────
CLEANING_MODES = {
    "CONSERVADOR": STOPWORDS_BASIC | LEGAL_SUFFIXES,
    # v0.17.1 — BALANCEADO vuelve a incluir ORGANIZATIONAL_TERMS.
    #
    # Historia, porque el error costó una corrida de 4,4 M de filas: en
    # v0.17.0 se quitó esa lista para arreglar los nombres que quedaban
    # degenerados ("BODEGA DE MODA S.A.S." → "S S"). La medición posterior
    # mostró que el arreglo real de ese defecto es la salvaguarda de
    # contenido de `TextProcessor` (nombres degenerados: 48 → 46 al quitar la
    # lista: NO era la lista). Quitarla, en cambio, alargó los nombres 17,5 →
    # 24,8 caracteres (+42 % de n-gramas) y disparó los trigramas genéricos
    # ("ION" en el 25 % de los nombres), con este costo medido sobre el
    # universo real del RUES: firmas 4:05 → 7:45, indexación 4:29 → 7:33 y
    # candidatos 15:51 → 41:10 con 2,59 M → 3,05 M de pares.
    #
    # La separación correcta no es "una lista u otra": bloqueo y scoring
    # tienen requisitos OPUESTOS, así que 0.17.1 los separa en dos
    # columnas. BALANCEADO conserva los giros (nombre fiel para decidir);
    # la poda vive en VOCABULARIO_SOLO_BLOQUEO, abajo, y solo toca la firma.
    "BALANCEADO": STOPWORDS_BASIC | LEGAL_SUFFIXES,
    "AGRESIVO": STOPWORDS_BASIC | LEGAL_SUFFIXES | ORGANIZATIONAL_TERMS,
}

#: v0.17.1 — vocabulario que se poda SOLO para construir la firma de bloqueo.
#:
#: Bloqueo y scoring tienen requisitos opuestos y hasta 0.17.0 compartían una
#: sola columna, que es el defecto de fondo que costó la corrida de 4,4 M:
#:
#:   - El BLOQUEO (MinHash/LSH) quiere nombres CORTOS y DISTINTIVOS: cada
#:     token genérico ("SERVICIOS", "COLOMBIA", "INTERNACIONAL") agrega
#:     n-gramas que casi todas las empresas comparten, así que infla el costo
#:     de la firma y llena los buckets de colisiones inútiles.
#:   - El SCORING quiere nombres FIELES: "EMPAQUES DEL CAUCA" y "COOPERATIVA
#:     DE CAFICULTORES DEL CAUCA" solo se distinguen por los tokens que el
#:     bloqueo querría podar.
#:
#: Con dos columnas cada fase obtiene lo que necesita: `NOMBRE_BLOQUEO` para
#: la firma y `NOMBRE_LIMPIO` para decidir. Un candidato de más solo cuesta
#: un score; un candidato de menos es un enlace perdido para siempre.
VOCABULARIO_SOLO_BLOQUEO: frozenset[str] = frozenset(ORGANIZATIONAL_TERMS)
