"""paises.catalogo — nombres de país en español con sus grafías (v0.22.0; ampliado en 0.22.4).

Por qué un catálogo declarado y no similitud de cadenas: en bases reales de
comercio exterior conviven ``TURQUIA``/``TURKIYE``, ``CHEQUIA``/``REPUBLICA
CHECA``, ``YIBUTI``/``DJIBOUTI`` y ``COSTA DE MARFIL``/``COTE D'IVOIRE``.
Ningún comparador de texto une esos pares. Y varios que SÍ se parecen mucho
—``GUINEA`` / ``GUINEA ECUATORIAL`` / ``GUINEA-BISSAU``, ``CONGO`` /
``REPUBLICA DEMOCRATICA DEL CONGO``— son países distintos: el fuzzy matching
los uniría. Es un problema de diccionario, y el diccionario es un dato
versionado y auditable, no un artefacto del dataset de turno.

Misma doctrina que ``matching.normalizadores.LOCALES``.

Formato: ``(ISO 3166-1 alfa-3, NOMBRE CANÓNICO, (alias adicionales, ...))``.
Los alias se comparan sin tildes, en mayúsculas y sin puntuación, así que no
hace falta declarar variantes de acentuación ni de puntuación.
"""

from __future__ import annotations

__all__ = ["CATALOGO_PAISES", "ETIQUETA_NO_PAIS", "ISO_NO_PAIS", "PATRONES_NO_PAIS"]

#: Catálogo base: 214 países, 378 grafías. Amplíelo pasando ``catalogo=`` a
#: :func:`record_linkage.paises.canonizar_pais`; no lo edite en el paquete.
CATALOGO_PAISES: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    (
        "USA",
        "ESTADOS UNIDOS",
        (
            "ESTADOS UNIDOS DE AMERICA",
            "EEUU",
            "EE UU",
            "USA",
            "UNITED STATES",
            "UNITED STATES OF AMERICA",
            "US",
        ),
    ),
    ("ECU", "ECUADOR", ()),
    ("PAN", "PANAMA", ()),
    ("PER", "PERU", ()),
    ("MEX", "MEXICO", ()),
    (
        "VEN",
        "VENEZUELA",
        ("VENEZUELA (REPUBLICA BOLIVARIANA DE)", "REPUBLICA BOLIVARIANA DE VENEZUELA"),
    ),
    ("DOM", "REPUBLICA DOMINICANA", ("REP DOMINICANA",)),
    ("CAN", "CANADA", ()),
    ("CRI", "COSTA RICA", ()),
    ("ESP", "ESPANA", ("SPAIN",)),
    ("GTM", "GUATEMALA", ()),
    ("CHL", "CHILE", ()),
    ("BRA", "BRASIL", ("BRAZIL",)),
    ("NLD", "PAISES BAJOS", ("PAISES BAJOS (REINO DE LOS)", "HOLANDA", "NETHERLANDS")),
    ("SLV", "EL SALVADOR", ("SALVADOR",)),
    ("HND", "HONDURAS", ()),
    ("PRI", "PUERTO RICO", ()),
    ("DEU", "ALEMANIA", ("GERMANY", "REPUBLICA FEDERAL DE ALEMANIA")),
    ("CHN", "CHINA", ("REPUBLICA POPULAR CHINA", "CHINA CONTINENTAL")),
    ("KAZ", "KAZAJSTAN", ("KAZAJISTAN", "KAZAKHSTAN")),
    ("ARG", "ARGENTINA", ()),
    (
        "GBR",
        "REINO UNIDO",
        (
            "REINO UNIDO DE GRAN BRETANA E IRLANDA DEL NORTE",
            "GRAN BRETANA",
            "INGLATERRA",
            "UNITED KINGDOM",
        ),
    ),
    ("ARE", "EMIRATOS ARABES UNIDOS", ("EAU",)),
    ("ITA", "ITALIA", ()),
    ("JPN", "JAPON", ()),
    ("BEL", "BELGICA", ()),
    ("FRA", "FRANCIA", ()),
    ("NIC", "NICARAGUA", ()),
    ("ABW", "ARUBA", ()),
    ("CUW", "CURAZAO", ("CURACAO",)),
    ("BOL", "BOLIVIA", ("BOLIVIA (ESTADO PLURINACIONAL DE)", "ESTADO PLURINACIONAL DE BOLIVIA")),
    ("POL", "POLONIA", ()),
    ("CUB", "CUBA", ()),
    ("IND", "INDIA", ()),
    ("AUS", "AUSTRALIA", ()),
    ("JAM", "JAMAICA", ()),
    (
        "KOR",
        "COREA DEL SUR",
        (
            "COREA (SUR) REPUBLICA DE",
            "COREA (SUR) REP DE",
            "REPUBLICA DE COREA",
            "COREA SUR",
            "COREA",
        ),
    ),
    ("URY", "URUGUAY", ()),
    ("SAU", "ARABIA SAUDITA", ("ARABIA SAUDI",)),
    ("PRY", "PARAGUAY", ()),
    ("RUS", "RUSIA", ("FEDERACION DE RUSIA", "FEDERACION RUSA")),
    ("TWN", "TAIWAN", ("TAIWAN (PROVINCIA DE CHINA)", "FORMOSA")),
    ("TTO", "TRINIDAD Y TOBAGO", ("TRINIDAD Y TABAGO",)),
    (
        "HKG",
        "HONG KONG",
        (
            "CHINA, REGION ADMINISTRATIVA ESPECIAL DE HONG KONG",
            "CHINA REGION ADMINISTRATIVA ESPECIAL DE HONG KONG",
            "HONG KONG (CHINA)",
        ),
    ),
    ("CHE", "SUIZA", ()),
    ("GUY", "GUYANA", ()),
    ("TUR", "TURQUIA", ("TURKIYE", "TURKEY")),
    ("PRT", "PORTUGAL", ()),
    ("ISR", "ISRAEL", ()),
    ("THA", "TAILANDIA", ()),
    ("MYS", "MALASIA", ("MALAYSIA",)),
    ("SGP", "SINGAPUR", ("SINGAPORE",)),
    ("QAT", "QATAR", ("CATAR",)),
    ("HTI", "HAITI", ()),
    ("KWT", "KUWAIT", ()),
    ("CZE", "CHEQUIA", ("REPUBLICA CHECA",)),
    ("BRB", "BARBADOS", ()),
    ("EGY", "EGIPTO", ()),
    ("GRC", "GRECIA", ()),
    ("IDN", "INDONESIA", ()),
    ("VNM", "VIET NAM", ("VIETNAM",)),
    ("SUR", "SURINAME", ("SURINAM",)),
    ("SWE", "SUECIA", ()),
    ("ROU", "RUMANIA", ("RUMANIA (RUMANIA)", "ROMANIA")),
    ("BHS", "BAHAMAS", ()),
    ("BLZ", "BELICE", ("BELIZE",)),
    ("HUN", "HUNGRIA", ()),
    ("OMN", "OMAN", ()),
    ("NOR", "NORUEGA", ()),
    ("AUT", "AUSTRIA", ()),
    ("UKR", "UCRANIA", ()),
    ("PHL", "FILIPINAS", ()),
    ("DNK", "DINAMARCA", ()),
    ("GLP", "GUADALUPE", ()),
    ("IRL", "IRLANDA", ("IRLANDA (EIRE)", "EIRE")),
    ("NGA", "NIGERIA", ()),
    ("LBN", "LIBANO", ()),
    ("NZL", "NUEVA ZELANDA", ("NUEVA ZELANDIA",)),
    ("KGZ", "KIRGUISTAN", ("KIRGUIZISTAN", "KYRGYZSTAN")),
    ("LCA", "SANTA LUCIA", ()),
    ("EST", "ESTONIA", ()),
    ("BHR", "BAHREIN", ()),
    ("JOR", "JORDANIA", ()),
    ("UZB", "UZBEKISTAN", ()),
    (
        "ZAF",
        "SUDAFRICA",
        ("SUDAFRICA, REPUBLICA DE", "SUDAFRICA REPUBLICA DE", "REPUBLICA DE SUDAFRICA"),
    ),
    ("FIN", "FINLANDIA", ()),
    ("MAR", "MARRUECOS", ()),
    ("MTQ", "MARTINICA", ()),
    ("BLR", "BELARUS", ("BIELORRUSIA",)),
    ("SVN", "ESLOVENIA", ()),
    ("BGR", "BULGARIA", ()),
    ("LBY", "LIBIA", ()),
    ("LVA", "LETONIA", ()),
    ("CYM", "ISLAS CAIMAN", ("CAIMAN ISLAS", "CAIMAN, ISLAS")),
    ("AZE", "AZERBAIYAN", ("AZERBAIJAN",)),
    ("GRD", "GRANADA", ("GRENADA",)),
    ("ATG", "ANTIGUA Y BARBUDA", ()),
    ("GHA", "GHANA", ()),
    ("PAK", "PAKISTAN", ()),
    ("GEO", "GEORGIA", ()),
    ("IRQ", "IRAQ", ("IRAK",)),
    ("DZA", "ARGELIA", ()),
    ("SVK", "ESLOVAQUIA", ()),
    ("CIV", "COSTA DE MARFIL", ("COTE D'IVOIRE", "COTE DIVOIRE", "COTE D IVOIRE")),
    ("GAB", "GABON", ()),
    ("VCT", "SAN VICENTE Y LAS GRANADINAS", ()),
    ("DMA", "DOMINICA", ()),
    ("HRV", "CROACIA", ()),
    ("AGO", "ANGOLA", ()),
    ("ARM", "ARMENIA", ()),
    ("GUF", "GUAYANA FRANCESA", ()),
    ("LTU", "LITUANIA", ()),
    ("TCA", "ISLAS TURCAS Y CAICOS", ("TURCAS Y CAICOS, ISLAS", "TURCAS Y CAICOS ISLAS")),
    ("MNE", "MONTENEGRO", ()),
    ("KEN", "KENIA", ("KENYA",)),
    ("LKA", "SRI LANKA", ()),
    ("TGO", "TOGO", ()),
    ("CMR", "CAMERUN", ("CAMERUN REP UNIDA DEL", "REPUBLICA UNIDA DEL CAMERUN")),
    ("ETH", "ETIOPIA", ()),
    ("SEN", "SENEGAL", ()),
    ("COG", "CONGO", ("CONGO REPUBLICA DEL", "REPUBLICA DEL CONGO", "CONGO BRAZZAVILLE")),
    ("MDA", "MOLDOVA", ("REPUBLICA DE MOLDOVA", "MOLDAVIA")),
    ("LBR", "LIBERIA", ()),
    ("UGA", "UGANDA", ()),
    ("ALB", "ALBANIA", ()),
    ("DJI", "DJIBOUTI", ("YIBUTI",)),
    (
        "COD",
        "REPUBLICA DEMOCRATICA DEL CONGO",
        ("REPUBDEMOCRATICA DEL CONGO", "CONGO KINSHASA", "ZAIRE"),
    ),
    ("BIH", "BOSNIA Y HERZEGOVINA", ("BOSNIA", "BOSNIA-HERZEGOVINA", "BOSNIA HERZEGOVINA")),
    ("MLT", "MALTA", ()),
    ("COL", "COLOMBIA", ()),
    ("TUN", "TUNEZ", ("TUNICIA",)),
    ("CYP", "CHIPRE", ()),
    ("SRB", "SERBIA", ()),
    (
        "VGB",
        "ISLAS VIRGENES BRITANICAS",
        (
            "VIRGENES ISLAS (BRITANICAS)",
            "VIRGENES ISLAS (REINO UNIDO)",
            "ISLAS VIRGENES (BRITANICAS)",
        ),
    ),
    ("MOZ", "MOZAMBIQUE", ()),
    ("BMU", "BERMUDAS", ("BERMUDA",)),
    (
        "TZA",
        "TANZANIA",
        ("TANZANIA, REPUBLICA UNIDA DE", "TANZANIA REP UNIDA DE", "REPUBLICA UNIDA DE TANZANIA"),
    ),
    ("GIN", "GUINEA", ()),
    ("LUX", "LUXEMBURGO", ()),
    ("BGD", "BANGLADESH", ()),
    ("GNQ", "GUINEA ECUATORIAL", ()),
    (
        "KNA",
        "SAN CRISTOBAL Y NIEVES",
        ("SAINT KITTS Y NEVIS", "SANCRISTOBAL Y NIEVES", "SAN CRISTOBAL Y NEVIS"),
    ),
    ("MDG", "MADAGASCAR", ()),
    ("MUS", "MAURICIO", ()),
    ("CPV", "CABO VERDE", ()),
    (
        "VIR",
        "ISLAS VIRGENES DE LOS ESTADOS UNIDOS",
        (
            "VIRGENES ISLAS (ESTADOS UNIDO",
            "VIRGENES ISLAS (ESTADOS UNIDOS)",
            "ISLAS VIRGENES (EEUU)",
            "ISLAS VIRGENES ESTADOUNIDENSES",
            "ISLAS VIRGENES DE EEUU",
            "ISLAS VIRGENES AMERICANAS",
        ),
    ),
    ("GUM", "GUAM", ()),
    ("ZWE", "ZIMBABWE", ("ZIMBABUE",)),
    ("NCL", "NUEVA CALEDONIA", ()),
    ("MDV", "MALDIVAS", ()),
    (
        "MKD",
        "MACEDONIA DEL NORTE",
        (
            "MACEDONIA",
            "REPUBLICA DE MACEDONIA",
            "REPUBLICA DE MACEDONIA DEL NORTE",
            "ANTIGUA REPUBLICA YUGOSLAVA DE MACEDONIA",
        ),
    ),
    ("MLI", "MALI", ()),
    ("NAM", "NAMIBIA", ()),
    ("BEN", "BENIN", ()),
    ("KHM", "CAMBOYA", ("CAMBOYA (KAMPUCHEA)", "KAMPUCHEA")),
    ("SDN", "SUDAN", ()),
    ("MRT", "MAURITANIA", ()),
    ("ZMB", "ZAMBIA", ()),
    ("ISL", "ISLANDIA", ()),
    ("BRN", "BRUNEI DARUSSALAM", ("BRUNEI",)),
    ("TJK", "TAYIKISTAN", ("TADJIKISTAN",)),
    ("YEM", "YEMEN", ()),
    ("AIA", "ANGUILA", ("ANGUILLA",)),
    ("SLE", "SIERRA LEONA", ()),
    (
        "MAC",
        "MACAO",
        (
            "CHINA, REGION ADMINISTRATIVA ESPECIAL DE MACAO",
            "CHINA REGION ADMINISTRATIVA ESPECIAL DE MACAO",
        ),
    ),
    ("MCO", "MONACO", ()),
    ("TCD", "CHAD", ()),
    ("PYF", "POLINESIA FRANCESA", ()),
    ("PSE", "ESTADO DE PALESTINA", ("PALESTINA",)),
    ("SYR", "SIRIA", ("SIRIA, REPUBLICA ARABE DE", "SIRIA REP ARABE DE", "REPUBLICA ARABE SIRIA")),
    ("REU", "REUNION", ()),
    (
        "PRK",
        "COREA DEL NORTE",
        ("REPUBLICA POPULAR DEMOCRATICA DE COREA", "COREA (NORTE) REPPOPDEM DE", "COREA NORTE"),
    ),
    ("COM", "COMORAS", ()),
    ("GNB", "GUINEA-BISSAU", ("GUINEA BISSAU", "GUINEA - BISSAU", "GUINEA-BISAU", "GUINEA BISAU")),
    ("MNG", "MONGOLIA", ()),
    ("BFA", "BURKINA FASO", ()),
    ("SYC", "SEYCHELLES", ()),
    ("CAF", "REPUBLICA CENTROAFRICANA", ()),
    ("PNG", "PAPUA NUEVA GUINEA", ("PAPUASIA NUEVA GUINEA",)),
    ("RWA", "RUANDA", ("RWANDA",)),
    ("MSR", "MONTSERRAT", ("MONTSERRAT ISLA",)),
    ("FJI", "FIJI", ("FIDJI", "FIYI", "ISLAS FIJI")),
    ("IOT", "TERRITORIO BRITANICO DEL OCEANO INDICO", ("T BRIT OCEANO INDICO",)),
    ("BES", "BONAIRE, SAN EUSTAQUIO Y SABA", ()),
    ("GMB", "GAMBIA", ()),
    ("SWZ", "ESWATINI", ("SUAZILANDIA",)),
    ("BDI", "BURUNDI", ()),
    ("BWA", "BOTSWANA", ("BOTSUANA",)),
    ("TON", "TONGA", ()),
    ("AND", "ANDORRA", ()),
    ("FSM", "MICRONESIA", ("MICRONESIA (ESTADOS FEDERADOS DE)",)),
    ("SOM", "SOMALIA", ()),
    ("MHL", "ISLAS MARSHALL", ("MARSHALL, ISLAS",)),
    ("NER", "NIGER", ()),
    ("NPL", "NEPAL", ()),
    ("LSO", "LESOTHO", ("LESOTO",)),
    ("TLS", "TIMOR ORIENTAL", ("TIMOR-LESTE",)),
    ("SMR", "SAN MARINO", ()),
    ("LAO", "LAOS", ("LAO, REPUBLICA DEMOCRATICA POPULAR DE", "LAOS REPPOP DEMOCRATICA DE")),
    ("MMR", "MYANMAR", ("BIRMANIA",)),
    ("TKM", "TURKMENISTAN", ()),
    ("ASM", "SAMOA AMERICANA", ()),
    ("MWI", "MALAWI", ()),
    # ── Añadidos en 0.22.4: aparecieron en `PAIS_ESTANDAR` de la vista
    # GOLD.VW_EXPORTACIONES_COLOMBIANAS_LECTURA_V2 y no estaban. Once países y
    # territorios ISO 3166-1 que la base DIAN de referencia nunca trajo.
    (
        "IRN",
        "IRAN",
        (
            "REPUBLICA ISLAMICA DE IRAN",
            "IRAN REPUBLICA ISLAMICA DEL",
            "IRAN (REPUBLICA ISLAMICA DE)",
            "IRAN, REPUBLICA ISLAMICA DEL",
        ),
    ),
    ("AFG", "AFGANISTAN", ("AFGHANISTAN",)),
    ("LIE", "LIECHTENSTEIN", ()),
    ("VUT", "VANUATU", ()),
    ("GIB", "GIBRALTAR", ()),
    ("NFK", "ISLA NORFOLK", ("ISLAS NORFOLK", "NORFOLK ISLAND")),
    ("SLB", "ISLAS SALOMON", ("SOLOMON ISLANDS",)),
    (
        "STP",
        "SANTO TOME Y PRINCIPE",
        ("SAO TOME Y PRINCIPE", "SAO TOME AND PRINCIPE", "SANTO TOME"),
    ),
    (
        "VAT",
        "CIUDAD DEL VATICANO",
        (
            "SANTA SEDE",
            "VATICANO",
            "ESTADO DE LA CIUDAD DEL VATICANO",
            "SANTA SEDE (CIUDAD DEL VATICANO)",
        ),
    ),
    ("MNP", "ISLAS MARIANAS DEL NORTE", ("MARIANAS DEL NORTE", "NORTHERN MARIANA ISLANDS")),
    ("WSM", "SAMOA", ("SAMOA OCCIDENTAL", "WESTERN SAMOA")),
)

#: Valores que NO son un país sino un usuario de zona franca colombiana. En la
#: base de importadores de referencia son 76 grafías y 397 filas cuyo "país de
#: destino final" es una zona franca: mezclarlas con destinos reales contamina
#: cualquier análisis por mercado.
PATRONES_NO_PAIS: tuple[str, ...] = (r"^ZONA\s+FRANCA\b", r"^ZFPE?\b", r"^ZF\b")

#: Etiqueta única con la que se agrupan los valores de PATRONES_NO_PAIS.
ETIQUETA_NO_PAIS = "ZONA FRANCA (COLOMBIA)"

#: Código reservado (fuera de ISO 3166) para esa etiqueta.
ISO_NO_PAIS = "ZZF"

#: Código reservado para lo que no se pudo clasificar.
ISO_SIN_CLASIFICAR = "ZZZ"

#: Etiqueta para lo que no se pudo clasificar.
ETIQUETA_SIN_CLASIFICAR = "SIN CLASIFICAR"
